"""Refresh macOS watcher's dependency notices from its checksum-pinned Cargo.lock.

Run from the repository root: uv run python -m tools.watcher_licenses
Downloads crates, verifies lockfile checksums and preserves their notice files.
This is a maintenance tool, not a build/install-time network operation.
"""

import hashlib
import io
import json
import tarfile
import tomllib
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.request import urlopen

from monophony_build import fetch

ROOT = Path(__file__).resolve().parents[1]


def collect(package):
    name, version = package["name"], package["version"]
    url = f"https://static.crates.io/crates/{name}/{name}-{version}.crate"
    with urlopen(url, timeout=60) as response:
        data = response.read(32 * 1024 * 1024)
    if hashlib.sha256(data).hexdigest() != package["checksum"]:
        raise ValueError(f"Checksum mismatch: {name} {version}")
    sections = [f"\n{'=' * 72}\n{name} {version}\n{url}\nSHA-256: {package['checksum']}\n"]
    with tarfile.open(fileobj=io.BytesIO(data)) as archive:
        metadata = tomllib.loads(
            archive.extractfile(f"{name}-{version}/Cargo.toml").read().decode()
        )
        sections.append(
            "Declared license: " + metadata["package"].get("license", "see license file") + "\n"
        )
        found = False
        for member in archive:
            basename = Path(member.name).name.upper()
            if member.isfile() and any(
                basename.startswith(prefix)
                for prefix in ("LICENSE", "COPYING", "COPYRIGHT", "NOTICE", "AUTHORS")
            ):
                sections.append(
                    f"\n--- {member.name} ---\n"
                    + archive.extractfile(member).read().decode("utf-8")
                )
                found = True
        if not found and metadata["package"].get("license") == "CC0-1.0":
            sections.append(
                "Dedicated to the public domain under CC0-1.0.\nAuthors: "
                + ", ".join(metadata["package"].get("authors", []))
                + "\n"
            )
            found = True
        if not found:
            raise ValueError(f"No bundled license files for {name} {version}; review manually")
    return "\n".join(sections)


def notices(source, version):
    with tarfile.open(fileobj=io.BytesIO(source)) as archive:
        lock = next(m for m in archive if m.name.endswith("/Cargo.lock"))
        packages = tomllib.loads(archive.extractfile(lock).read().decode())["package"]
    excluded = {
        "fuchsia-zircon",
        "fuchsia-zircon-sys",
        "inotify",
        "inotify-sys",
        "hermit-abi",
        "redox_syscall",
        "kernel32-sys",
        "miow",
        "ws2_32-sys",
    }
    packages = [
        p
        for p in packages
        if "checksum" in p and p["name"] not in excluded and not p["name"].startswith("winapi")
    ]
    with ThreadPoolExecutor(max_workers=8) as executor:
        sections = list(executor.map(collect, packages))
    heading = (
        "Dependency notices for autozimu/unison-fsmonitor "
        + version
        + ".\nCargo.lock dependency notices (non-macOS OS bindings omitted).\n"
        + "Generated by tools/watcher_licenses.py from checksum-verified crates.\n"
    )
    return heading + "".join(sections)


def main():
    manifest = json.loads((ROOT / "unison-artifacts.json").read_text())
    result = notices(fetch(manifest["watcher_source"]), manifest["watcher_version"])
    (ROOT / "third_party/watcher-dependency-notices.txt").write_text(result, encoding="utf-8")
    print("Refreshed checksum-verified watcher dependency notices")


if __name__ == "__main__":
    main()
